---
name: Feature request
about: Suggest an idea for this project
title: ''
labels: enhancement
assignees: ''

---

**Feature type**
What type of feature it is

**Breaking change**
Whether the change will break current functionality (Yes/No)

**Proposed Functionality**
Describe in detail the new feature or behavior you'd like to propose. Include any specific changes to work flows, data models, or the user interface.

**Use Case**
Explain how adding this functionality would benefit users. What need does it address?

**Additional context**
Add any other context or screenshots about the feature request here.
