name: Deploy

on:
  push:
    branches:
      - master

jobs:
    deploy:
      name: Deploy to Hex and create release
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2
        - uses: erlef/setup-beam@v1
          with:
            otp-version: '24'
            elixir-version: '1.12.0'
        - uses: actions/cache@v2
          with:
            path: deps
            key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
            restore-keys: |
              ${{ runner.os }}-mix-
        - run: mix deps.get
        - run: mix compile --warnings-as-errors
        - run: mix hex.publish --yes
          env:
            HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
